# Test configuration for Travis CI. See <https://travis-ci.org/>.
language: cpp

matrix:
  include:
    - os: linux
      dist: xenial
      addons:
        apt:
          packages:
            - g++-5
            - pkg-config
            - libncurses5-dev
            - libncursesw5-dev
            - zlib1g-dev 
            - libssl-dev
            - liblz4-dev
            - libcurl4-openssl-dev 
            - liblz-dev
            - libbz2-dev
            - liblzma-dev
          sources: &sources
            - ubuntu-toolchain-r-test
      env:
        - COMPILERS="CC=gcc-5 && CXX=g++-5"

    - os: linux
      dist: xenial
      addons:
        apt:
          packages:
            - g++-6
            - pkg-config
            - libncurses5-dev
            - libncursesw5-dev
            - zlib1g-dev 
            - libssl-dev
            - liblz4-dev
            - libcurl4-openssl-dev 
            - liblz-dev
            - libbz2-dev
            - liblzma-dev
          sources: &sources
            - ubuntu-toolchain-r-test
      env:
        - COMPILERS="CC=gcc-6 && CXX=g++-6"

    - os: linux
      dist: xenial
      addons:
        apt:
          packages:
            - g++-7
            - pkg-config
            - libncurses5-dev
            - libncursesw5-dev
            - zlib1g-dev 
            - libssl-dev
            - liblz4-dev
            - libcurl4-openssl-dev 
            - liblz-dev
            - libbz2-dev
            - liblzma-dev
          sources: &sources
            - ubuntu-toolchain-r-test
      env:
        - COMPILERS="CC=gcc-7 && CXX=g++-7"

    - os: linux
      dist: xenial
      addons:
        apt:
          packages:
            - g++-8
            - pkg-config
            - libncurses5-dev
            - libncursesw5-dev
            - zlib1g-dev 
            - libssl-dev
            - liblz4-dev
            - libcurl4-openssl-dev 
            - liblz-dev
            - libbz2-dev
            - liblzma-dev
          sources: &sources
            - ubuntu-toolchain-r-test
      env:
        - COMPILERS="CC=gcc-8 && CXX=g++-8"

    - os: linux
      dist: xenial
      addons:
        apt:
          packages:
            - mingw-w64
      env:
        - COMPILERS="CC=x86_64-w64-mingw32-gcc-posix && CXX=x86_64-w64-mingw32-g++-posix"

before_install:
  # Overwrite default CC and CXX
  - eval "${COMPILERS}"
  - git clone https://github.com/facebook/zstd && cd zstd && make -j 4 && sudo make install && cd ..
  - git clone https://github.com/lz4/lz4 && cd lz4 && make -j 4 && sudo make install && cd ..
  - git clone https://github.com/samtools/htslib && cd htslib && autoheader && autoconf && ./configure && make -j 4 && sudo make install && cd ..

script:
  - ./autogen.sh && ./configure && make -j4 && make install